// ===== キャラの固定データ =====
// このファイルは tools/convert_master.py で data/master.xlsx から作っています。
// 直接書き換えても動きますが、次に変換したときに Excel の内容で上書きされます。

const CHARACTERS = [
    {"no": 3, "name": "三日月宗近-戦装束", "base": "三日月宗近", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": [], "secretColor": "", "skillValue": "", "skillName": "", "skills": {}, "levels": {}, "limitBreaks": []},
    {"no": 3, "name": "三日月宗近-戦装束-レア", "base": "三日月宗近", "costume": "戦装束", "rarity": "レア", "swordType": "太刀", "yukari": ["夜", "天下五剣"], "secretColor": "赤", "skillValue": 22, "skillName": "月明かりの冴え", "skills": {"1": "【すべて】のト餓鬼を消去し、敵に【特小++】ダメージを与える"}, "levels": {"13": [1060, 140]}, "limitBreaks": []},
    {"no": 5, "name": "小狐丸-戦装束", "base": "小狐丸", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 27, "skillName": "ボム練成の術 三の火", "skills": {"1": "ボムを【3個】生成する"}, "levels": {"5": [740, 77]}, "limitBreaks": []},
    {"no": 7, "name": "石切丸-戦装束", "base": "石切丸", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["ご神刀"], "secretColor": "青", "skillValue": 22, "skillName": "逆さ扇斬り 守護の型", "skills": {"1": "【扇型・中範囲】のト餓鬼を消去し、敵に【特小－】ダメージを与える。\n味方全員に被ダメージ軽減【極小＋・3手】を付与する"}, "levels": {"1": [561, 61]}, "limitBreaks": []},
    {"no": 9, "name": "岩融-戦装束", "base": "岩融", "costume": "戦装束", "rarity": "通常", "swordType": "薙刀", "yukari": ["源氏"], "secretColor": "青", "skillValue": 16, "skillName": "大薙ぎ払い・赤", "skills": {"1": "【最大10体】の赤ト餓鬼を盤面の右下に集める"}, "levels": {"1": [471, 69]}, "limitBreaks": []},
    {"no": 23, "name": "鳴狐-戦装束", "base": "鳴狐", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 21, "skillName": "ボム練成の術 二の火", "skills": {"1": "ボムを【2個】生成する"}, "levels": {"28": [1505, 223]}, "limitBreaks": []},
    {"no": 25, "name": "一期一振-戦装束", "base": "一期一振", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 22, "skillName": "水平一刀斬り", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【特小＋＋】ダメージを与える"}, "levels": {"11": [1050, 108]}, "limitBreaks": []},
    {"no": 25, "name": "一期一振-戦装束-レア", "base": "一期一振", "costume": "戦装束", "rarity": "レア", "swordType": "太刀", "yukari": ["兄弟", "炎"], "secretColor": "黄", "skillValue": 22, "skillName": "華々しき雄飛への導き", "skills": {"2": "自身・脇差・短刀にブレイク力上昇【大・6手】を付与する\n自身・脇差・短刀に攻撃力上昇【特小＋・6手】を付与する\nバリア【1回】を付与する"}, "levels": {"24": [1673, 173]}, "limitBreaks": []},
    {"no": 27, "name": "鯰尾藤四郎-戦装束", "base": "鯰尾藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 15, "skillName": "大薙ぎ払い・青", "skills": {"1": "【最大10体】の青ト餓鬼を盤面の下に集める"}, "levels": {"22": [1357, 188]}, "limitBreaks": []},
    {"no": 29, "name": "骨喰藤四郎-戦装束", "base": "骨喰藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 14, "skillName": "色変幻の術・青", "skills": {"1": "青以外のト餓鬼を【最大10体】、青色に変換する"}, "levels": {"16": [1024, 163]}, "limitBreaks": []},
    {"no": 31, "name": "平野藤四郎-戦装束", "base": "平野藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "青", "skillValue": 14, "skillName": "色変幻の術・赤", "skills": {"1": "黄色のト餓鬼を【最大10体】、赤色に変換する"}, "levels": {"30": [1691, 232]}, "limitBreaks": []},
    {"no": 33, "name": "厚藤四郎-戦装束", "base": "厚藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 14, "skillName": "色変幻の術・青", "skills": {"1": "赤色のト餓鬼を【最大10体】、青色に変換する"}, "levels": {"1": [440, 77]}, "limitBreaks": []},
    {"no": 45, "name": "乱藤四郎-戦装束", "base": "乱藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 12, "skillName": "色変幻の術・乱", "skills": {"1": "ト餓鬼を【最大10体】、ランダムな色に変換する"}, "levels": {"10": [905, 100]}, "limitBreaks": []},
    {"no": 45, "name": "乱藤四郎-戦装束-レア", "base": "乱藤四郎", "costume": "戦装束", "rarity": "レア", "swordType": "短刀", "yukari": [], "secretColor": "", "skillValue": "", "skillName": "", "skills": {}, "levels": {}, "limitBreaks": []},
    {"no": 47, "name": "五虎退-戦装束", "base": "五虎退", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 13, "skillName": "ボム練成の術 一の火", "skills": {"1": "ボムを【1個】生成する"}, "levels": {"1": [477, 56]}, "limitBreaks": []},
    {"no": 59, "name": "蛍丸-戦装束", "base": "蛍丸", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["夜"], "secretColor": "青", "skillValue": 36, "skillName": "正円一刀斬り", "skills": {"1": "【円型・大範囲】のト餓鬼を消去し、敵に【中＋】ダメージを与える"}, "levels": {"6": [677, 107]}, "limitBreaks": []},
    {"no": 65, "name": "蜻蛉切-戦装束", "base": "蜻蛉切", "costume": "戦装束", "rarity": "通常", "swordType": "槍", "yukari": ["天下三名槍"], "secretColor": "黄", "skillValue": 22, "skillName": "必中縦断突き", "skills": {"1": "指定した【縦列・小範囲】のト餓鬼を消去し、敵に【小】ダメージを与える"}, "levels": {"1": [551, 72]}, "limitBreaks": []},
    {"no": 79, "name": "江雪左文字-戦装束", "base": "江雪左文字", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": [], "secretColor": "", "skillValue": "", "skillName": "", "skills": {}, "levels": {}, "limitBreaks": []},
    {"no": 85, "name": "加州清光-戦装束", "base": "加州清光", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 26, "skillName": "必中三段斬り", "skills": {"1": "指定した【円型・特小範囲】のト餓鬼を3回消去し、敵に【小】ダメージを与える"}, "levels": {"5": [645, 73]}, "limitBreaks": []},
    {"no": 91, "name": "和泉守兼定-戦装束", "base": "和泉守兼定", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 33, "skillName": "正円二段斬り", "skills": {"1": "ランダムな場所の【円型・小範囲】のト餓鬼を2回消去し、敵に【中】ダメージを与える"}, "levels": {"20": [1551, 188]}, "limitBreaks": []},
    {"no": 93, "name": "陸奥守吉行-戦装束", "base": "陸奥守吉行", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["海"], "secretColor": "黄", "skillValue": 16, "skillName": "", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【極小】ダメージを与える味方全員に攻撃力上昇【極小++・3手】を付与する"}, "levels": {"30": [1575, 228]}, "limitBreaks": [{"from": 30, "to": 35, "materials": {"黄の絵具": 1, "書き物道具": 2, "花札": 2, "天ぷら": 2, "そろばん": 2, "打刀の心得": 1}}]},
    {"no": 95, "name": "山姥切国広-戦装束", "base": "山姥切国広", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["兄弟"], "secretColor": "青", "skillValue": 22, "skillName": "正円一刀斬り", "skills": {"1": "【円型・小範囲】のト餓鬼を消去し、敵に【小】ダメージを与える"}, "levels": {"10": [850, 107]}, "limitBreaks": []},
    {"no": 97, "name": "山伏国広-戦装束", "base": "山伏国広", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": [], "secretColor": "", "skillValue": "", "skillName": "", "skills": {}, "levels": {}, "limitBreaks": []},
    {"no": 122, "name": "獅子王-戦装束", "base": "獅子王", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 22, "skillName": "水平一刀斬り", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【小＋】ダメージを与える"}, "levels": {"5": [771, 74]}, "limitBreaks": []},
    {"no": 130, "name": "鶴丸国永-戦装束", "base": "鶴丸国永", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["鳥"], "secretColor": "赤", "skillValue": 24, "skillName": "水平斬り 攻勢の型", "skills": {"1": "【横列・中範囲】のト餓鬼を消去し、敵に【小＋】ダメージを与える\n自身に攻撃力上昇【極小・1手】を付与する"}, "levels": {"10": [935, 110]}, "limitBreaks": []},
];
