// ===== キャラの固定データ =====
// このファイルは tools/convert_master.py で data/master.xlsx から作っています。
// 直接書き換えても動きますが、次に変換したときに Excel の内容で上書きされます。

const CHARACTERS = [
    {"no": 3, "name": "三日月宗近-戦装束", "base": "三日月宗近", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["夜"], "secretColor": "赤", "skillValue": 22, "skillName": "正円白刃斬り", "skills": {"1": "【円型・小範囲】のト餓鬼を消去し、敵に【特小＋＋】ダメージを与える"}, "levels": {"1": [513, 67]}, "limitBreaks": []},
    {"no": 3, "name": "三日月宗近-戦装束-レア", "base": "三日月宗近", "costume": "戦装束", "rarity": "レア", "swordType": "太刀", "yukari": ["夜", "天下五剣"], "secretColor": "赤", "skillValue": 22, "skillName": "月明かりの冴え", "skills": {"1": "【すべて】のト餓鬼を消去し、敵に【特小++】ダメージを与える", "2": "【すべて】のト餓鬼を消去し、敵に【中－】ダメージを与える", "3": "【すべて】のト餓鬼を消去し、敵に【中－】ダメージを与える"}, "levels": {"1": [531, 70], "13": [1060, 140]}, "limitBreaks": []},
    {"no": 5, "name": "小狐丸-戦装束", "base": "小狐丸", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 27, "skillName": "ボム練成の術 三の火", "skills": {"1": "ボムを【3個】生成する"}, "levels": {"1": [556, 58], "5": [740, 77], "6": [786, 82], "7": [832, 87], "9": [924, 97], "10": [971, 102]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"水": 2, "ふさふさの毛": 2}}]},
    {"no": 7, "name": "石切丸-戦装束", "base": "石切丸", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["ご神刀"], "secretColor": "青", "skillValue": 22, "skillName": "逆さ扇斬り 守護の型", "skills": {"1": "【扇型・中範囲】のト餓鬼を消去し、敵に【特小－】ダメージを与える。\n味方全員に被ダメージ軽減【極小＋・3手】を付与する"}, "levels": {"1": [561, 61], "4": [700, 76], "5": [746, 81], "8": [886, 96], "10": [979, 106]}, "limitBreaks": []},
    {"no": 9, "name": "岩融-戦装束", "base": "岩融", "costume": "戦装束", "rarity": "通常", "swordType": "薙刀", "yukari": ["源氏"], "secretColor": "青", "skillValue": 16, "skillName": "大薙ぎ払い・赤", "skills": {"1": "【最大10体】の赤ト餓鬼を盤面の右下に集める"}, "levels": {"1": [471, 69], "4": [588, 86], "5": [627, 92]}, "limitBreaks": []},
    {"no": 11, "name": "今剣-戦装束", "base": "今剣", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["源氏"], "secretColor": "赤", "skillValue": 14, "skillName": "色変幻の術・赤", "skills": {"1": "赤以外のト餓鬼を【最大10体】、赤色に変換する"}, "levels": {"1": [459, 74]}, "limitBreaks": []},
    {"no": 19, "name": "にっかり青江-戦装束", "base": "にっかり青江", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["夜"], "secretColor": "赤", "skillValue": 15, "skillName": "守備制約の計", "skills": {"1": "敵に被ダメージ増加【極小＋・1手】を付与する"}, "levels": {"1": [524, 65]}, "limitBreaks": []},
    {"no": 23, "name": "鳴狐-戦装束", "base": "鳴狐", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 21, "skillName": "ボム練成の術 二の火", "skills": {"1": "ボムを【2個】生成する"}, "levels": {"1": [465, 69], "28": [1505, 223], "29": [1543, 229]}, "limitBreaks": []},
    {"no": 25, "name": "一期一振-戦装束", "base": "一期一振", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 22, "skillName": "水平一刀斬り", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【特小＋＋】ダメージを与える"}, "levels": {"1": [575, 59], "11": [1050, 108]}, "limitBreaks": []},
    {"no": 25, "name": "一期一振-戦装束-レア", "base": "一期一振", "costume": "戦装束", "rarity": "レア", "swordType": "太刀", "yukari": ["兄弟", "炎"], "secretColor": "黄", "skillValue": 22, "skillName": "華々しき雄飛への導き", "skills": {"2": "自身・脇差・短刀にブレイク力上昇【大・6手】を付与する\n自身・脇差・短刀に攻撃力上昇【特小＋・6手】を付与する\nバリア【1回】を付与する"}, "levels": {"1": [595, 62], "24": [1673, 173], "25": [1720, 178], "28": [1861, 192], "29": [1908, 197]}, "limitBreaks": []},
    {"no": 27, "name": "鯰尾藤四郎-戦装束", "base": "鯰尾藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 15, "skillName": "大薙ぎ払い・青", "skills": {"1": "【最大10体】の青ト餓鬼を盤面の下に集める"}, "levels": {"1": [495, 69], "22": [1357, 188], "23": [1398, 194]}, "limitBreaks": []},
    {"no": 29, "name": "骨喰藤四郎-戦装束", "base": "骨喰藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 14, "skillName": "色変幻の術・青", "skills": {"1": "青以外のト餓鬼を【最大10体】、青色に変換する"}, "levels": {"1": [457, 73], "16": [1024, 163], "17": [1062, 169], "18": [1100, 175]}, "limitBreaks": []},
    {"no": 31, "name": "平野藤四郎-戦装束", "base": "平野藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "青", "skillValue": 14, "skillName": "色変幻の術・赤", "skills": {"1": "黄色のト餓鬼を【最大10体】、赤色に変換する"}, "levels": {"1": [497, 68], "30": [1691, 232]}, "limitBreaks": [{"from": 30, "to": 35, "materials": {"青の絵具": 1, "書き物道具": 2, "囲碁": 2, "お味噌汁": 2, "そろばん": 2, "短刀の心得": 1}}]},
    {"no": 33, "name": "厚藤四郎-戦装束", "base": "厚藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 14, "skillName": "色変幻の術・青", "skills": {"1": "赤色のト餓鬼を【最大10体】、青色に変換する"}, "levels": {"1": [440, 77], "6": [622, 109], "7": [658, 115], "11": [804, 141], "12": [841, 148], "13": [877, 154], "14": [914, 161]}, "limitBreaks": []},
    {"no": 39, "name": "前田藤四郎-戦装束", "base": "前田藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 14, "skillName": "色変幻の術・黄", "skills": {"1": "青色のト餓鬼を【最大10体】、黄色に変換する"}, "levels": {"1": [565, 58]}, "limitBreaks": []},
    {"no": 41, "name": "秋田藤四郎-戦装束", "base": "秋田藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 15, "skillName": "受け流しの法", "skills": {"1": "味方全員にガード率上昇【中－・5手】を付与する"}, "levels": {"1": [473, 60]}, "limitBreaks": []},
    {"no": 45, "name": "乱藤四郎-戦装束", "base": "乱藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "黄", "skillValue": 12, "skillName": "色変幻の術・乱", "skills": {"1": "ト餓鬼を【最大10体】、ランダムな色に変換する"}, "levels": {"1": [518, 57], "10": [905, 100], "13": [1033, 114], "14": [1076, 118], "15": [1119, 123], "16": [1162, 128], "19": [1291, 142]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"葉っぱ": 2, "大豆": 2}}]},
    {"no": 45, "name": "乱藤四郎-戦装束-レア", "base": "乱藤四郎", "costume": "戦装束", "rarity": "レア", "swordType": "短刀", "yukari": ["兄弟", "花"], "secretColor": "赤", "skillValue": 16, "skillName": "百花乱々みだれ咲き", "skills": {"1": "味方全員に攻撃力上昇【極小＋＋・3手】を付与する\n敵に被ダメージ増加【極小＋・3手】を付与する"}, "levels": {"1": [532, 59]}, "limitBreaks": []},
    {"no": 47, "name": "五虎退-戦装束", "base": "五虎退", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 13, "skillName": "ボム練成の術 一の火", "skills": {"1": "ボムを【1個】生成する"}, "levels": {"1": [477, 56], "4": [595, 70], "5": [635, 74]}, "limitBreaks": []},
    {"no": 49, "name": "薬研藤四郎-戦装束", "base": "薬研藤四郎", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 16, "skillName": "真っ向斬り 攻勢の型", "skills": {"1": "【縦列・特小範囲】のト餓鬼を消去し、敵に【極小】ダメージを与える\n味方全員にクリティカル率上昇【小・3手】を付与する"}, "levels": {"1": [542, 55]}, "limitBreaks": []},
    {"no": 55, "name": "鶯丸-戦装束", "base": "鶯丸", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["鳥"], "secretColor": "赤", "skillValue": 22, "skillName": "霧散斬り・青", "skills": {"1": "ランダムな青ト餓鬼を【最大8体】消去し、敵に【小＋＋】ダメージを与える"}, "levels": {"1": [626, 54]}, "limitBreaks": []},
    {"no": 59, "name": "蛍丸-戦装束", "base": "蛍丸", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["夜"], "secretColor": "青", "skillValue": 36, "skillName": "正円一刀斬り", "skills": {"1": "【円型・大範囲】のト餓鬼を消去し、敵に【中＋】ダメージを与える"}, "levels": {"1": [479, 76], "6": [677, 107], "8": [756, 119], "13": [955, 150], "14": [994, 157]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"葉っぱ": 2, "大豆": 2}}]},
    {"no": 61, "name": "愛染国俊-戦装束", "base": "愛染国俊", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["炎"], "secretColor": "赤", "skillValue": 17, "skillName": "強攻の法", "skills": {"1": "自身に攻撃力上昇【特小・1手】を付与する\n自身に攻撃力上昇【極小＋・1手】を付与する"}, "levels": {"1": [483, 62]}, "limitBreaks": []},
    {"no": 65, "name": "蜻蛉切-戦装束", "base": "蜻蛉切", "costume": "戦装束", "rarity": "通常", "swordType": "槍", "yukari": ["天下三名槍"], "secretColor": "黄", "skillValue": 22, "skillName": "必中縦断突き", "skills": {"1": "指定した【縦列・小範囲】のト餓鬼を消去し、敵に【小】ダメージを与える"}, "levels": {"1": [551, 72], "4": [688, 90], "5": [733, 96]}, "limitBreaks": []},
    {"no": 73, "name": "燭台切光忠-戦装束", "base": "燭台切光忠", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["もの斬り"], "secretColor": "赤", "skillValue": 27, "skillName": "必中縦断斬り ボムの型", "skills": {"1": "指定した【縦列・小範囲】のト餓鬼を消去し、敵に【特小＋＋】ダメージを与える\nボムを【1個】生成する"}, "levels": {"1": [547, 66], "4": [682, 82], "5": [727, 87]}, "limitBreaks": []},
    {"no": 79, "name": "江雪左文字-戦装束", "base": "江雪左文字", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["雪"], "secretColor": "赤", "skillValue": 19, "skillName": "霧散斬り 先手の型", "skills": {"1": "ランダムなト餓鬼（攻撃指示優先）を最大5体消去し、敵に【特小＋＋】ダメージを与える\n消去時のブレイクゲージ減少量が【2倍】になる"}, "levels": {"1": [507, 74], "4": [633, 92], "5": [675, 98]}, "limitBreaks": []},
    {"no": 81, "name": "宗三左文字-戦装束", "base": "宗三左文字", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["蝶"], "secretColor": "赤", "skillValue": 15, "skillName": "攪乱戦術・黄", "skills": {"1": "【最大10体】の黄ト餓鬼を盤面の中央に集める"}, "levels": {"1": [493, 54], "4": [615, 67], "5": [656, 72]}, "limitBreaks": []},
    {"no": 83, "name": "小夜左文字-戦装束", "base": "小夜左文字", "costume": "戦装束", "rarity": "通常", "swordType": "短刀", "yukari": ["夜"], "secretColor": "赤", "skillValue": 27, "skillName": "正円斬り 追撃の型", "skills": {"1": "【円型・特小範囲】のト餓鬼を消去し、敵に【中】ダメージを与える。乱舞ぎりタイム中はさらにダメージ上昇。"}, "levels": {"1": [417, 81]}, "limitBreaks": []},
    {"no": 85, "name": "加州清光-戦装束", "base": "加州清光", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 26, "skillName": "必中三段斬り", "skills": {"1": "指定した【円型・特小範囲】のト餓鬼を3回消去し、敵に【小】ダメージを与える"}, "levels": {"1": [485, 55], "5": [645, 73], "6": [686, 77], "7": [726, 82], "9": [806, 91], "10": [847, 96]}, "limitBreaks": []},
    {"no": 87, "name": "大和守安定-戦装束", "base": "大和守安定", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 22, "skillName": "霧散斬り ボムの型", "skills": {"1": "ランダムな孤立した青ト餓鬼を【最大3体】消去し、敵に【特小＋】ダメージを与える\nボムを【1個】生成する"}, "levels": {"1": [467, 57]}, "limitBreaks": []},
    {"no": 89, "name": "歌仙兼定-戦装束", "base": "歌仙兼定", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["花"], "secretColor": "赤", "skillValue": 22, "skillName": "水平一刀斬り", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【小－】ダメージを与える"}, "levels": {"1": [475, 70]}, "limitBreaks": []},
    {"no": 89, "name": "歌仙兼定-戦装束-レア", "base": "歌仙兼定", "costume": "戦装束", "rarity": "レア", "swordType": "打刀", "yukari": ["詠み人", "花"], "secretColor": "赤", "skillValue": 16, "skillName": "くちなしの挽歌", "skills": {"1": "指定した【縦列・小範囲】のト餓鬼を、黄色に変化させる"}, "levels": {"1": [492, 74]}, "limitBreaks": []},
    {"no": 91, "name": "和泉守兼定-戦装束", "base": "和泉守兼定", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 33, "skillName": "正円二段斬り", "skills": {"1": "ランダムな場所の【円型・小範囲】のト餓鬼を2回消去し、敵に【中】ダメージを与える"}, "levels": {"1": [602, 73], "20": [1551, 188], "21": [1600, 194], "22": [1650, 200], "26": [1850, 224]}, "limitBreaks": [{"from": 20, "to": 30, "materials": {"紙": 2, "水": 2, "大豆": 2, "お花": 4}}]},
    {"no": 93, "name": "陸奥守吉行-戦装束", "base": "陸奥守吉行", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["海"], "secretColor": "黄", "skillValue": 16, "skillName": "水平斬り 攻勢の型", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【極小】ダメージを与える\n味方全員に攻撃力上昇【極小＋＋・3手】を付与する"}, "levels": {"1": [463, 67], "30": [1575, 228]}, "limitBreaks": [{"from": 30, "to": 35, "materials": {"黄の絵具": 1, "書き物道具": 2, "花札": 2, "天ぷら": 2, "そろばん": 2, "打刀の心得": 1}}]},
    {"no": 95, "name": "山姥切国広-戦装束", "base": "山姥切国広", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["兄弟"], "secretColor": "青", "skillValue": 22, "skillName": "正円一刀斬り", "skills": {"1": "【円型・小範囲】のト餓鬼を消去し、敵に【小】ダメージを与える"}, "levels": {"1": [487, 61], "10": [850, 107], "13": [971, 122], "14": [1011, 127], "15": [1052, 132]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"ふさふさの毛": 2, "麦": 2}}]},
    {"no": 97, "name": "山伏国広-戦装束", "base": "山伏国広", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["お山修行"], "secretColor": "赤", "skillValue": 22, "skillName": "逆さ扇斬り 守護の型", "skills": {"1": "【扇型・特小範囲】のト餓鬼を消去し、敵に【極小＋】ダメージを与える\n味方全員に被ダメージ軽減【特小＋＋・3手】を付与する"}, "levels": {"1": [584, 70], "4": [729, 87], "5": [777, 93], "10": [1019, 122]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"大豆": 2, "丸太": 2}}]},
    {"no": 99, "name": "堀川国広-戦装束", "base": "堀川国広", "costume": "戦装束", "rarity": "通常", "swordType": "脇差", "yukari": ["新選組"], "secretColor": "赤", "skillValue": 16, "skillName": "会心猛攻の法", "skills": {"1": "味方全員に攻撃力上昇【極小＋＋・3手】を付与する\n味方全員にクリティカル率上昇【特小＋＋・9手】を付与する"}, "levels": {"1": [491, 63]}, "limitBreaks": []},
    {"no": 101, "name": "蜂須賀虎徹-戦装束", "base": "蜂須賀虎徹", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["兄弟"], "secretColor": "赤", "skillValue": 16, "skillName": "霧散斬り 掃討の型", "skills": {"1": "孤立したト餓鬼をランダムに【最大5体】消去し、敵に【特小＋】ダメージを与える"}, "levels": {"1": [481, 71]}, "limitBreaks": []},
    {"no": 116, "name": "大倶利伽羅-戦装束", "base": "大倶利伽羅", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["龍"], "secretColor": "赤", "skillValue": 24, "skillName": "三段斬り 攻勢の型", "skills": {"1": "ランダムな【円型・特小範囲】のト餓鬼を3回消去し、敵に【小－】ダメージを与える\n自身にクリティカル率上昇【極小＋＋・1手】を付与する"}, "levels": {"1": [455, 72]}, "limitBreaks": []},
    {"no": 118, "name": "へし切長谷部-戦装束", "base": "へし切長谷部", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["もの斬り"], "secretColor": "赤", "skillValue": 27, "skillName": "必中二段斬り", "skills": {"1": "指定した【縦列・小範囲】のト餓鬼を2回消去し、敵に【小＋】ダメージを与える"}, "levels": {"1": [530, 65]}, "limitBreaks": []},
    {"no": 122, "name": "獅子王-戦装束", "base": "獅子王", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["けもの"], "secretColor": "赤", "skillValue": 22, "skillName": "水平一刀斬り", "skills": {"1": "【横列・小範囲】のト餓鬼を消去し、敵に【小＋】ダメージを与える"}, "levels": {"1": [579, 56], "5": [771, 74], "6": [819, 79], "7": [867, 84]}, "limitBreaks": []},
    {"no": 128, "name": "同田貫正国-戦装束", "base": "同田貫正国", "costume": "戦装束", "rarity": "通常", "swordType": "打刀", "yukari": ["もの斬り"], "secretColor": "赤", "skillValue": 22, "skillName": "真っ向一刀斬り", "skills": {"1": "【縦列・小範囲】のト餓鬼を消去し、敵に【小＋＋】ダメージを与える"}, "levels": {"1": [453, 75], "4": [565, 93], "5": [603, 99]}, "limitBreaks": []},
    {"no": 130, "name": "鶴丸国永-戦装束", "base": "鶴丸国永", "costume": "戦装束", "rarity": "通常", "swordType": "太刀", "yukari": ["鳥"], "secretColor": "赤", "skillValue": 24, "skillName": "水平斬り 攻勢の型", "skills": {"1": "【横列・中範囲】のト餓鬼を消去し、敵に【小＋】ダメージを与える\n自身に攻撃力上昇【極小・1手】を付与する"}, "levels": {"1": [536, 63], "10": [935, 110], "12": [1023, 120], "13": [1068, 125], "14": [1112, 130]}, "limitBreaks": [{"from": 10, "to": 20, "materials": {"水": 2, "ふさふさの毛": 2}}]},
    {"no": 132, "name": "太郎太刀-戦装束", "base": "太郎太刀", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["ご神刀"], "secretColor": "赤", "skillValue": 36, "skillName": "霧散斬り・黄", "skills": {"1": "黄ト餓鬼をランダムに【最大10体】消去し、敵に【小＋】ダメージを与える"}, "levels": {"1": [588, 64]}, "limitBreaks": []},
    {"no": 132, "name": "太郎太刀-戦装束-レア", "base": "太郎太刀", "costume": "戦装束", "rarity": "レア", "swordType": "大太刀", "yukari": ["ご神刀", "兄弟"], "secretColor": "赤", "skillValue": 33, "skillName": "天より墜つる暴威", "skills": {"1": "【円型・大範囲】のト餓鬼を消去し、敵に【中＋】ダメージを与える。ボスが被ダメージ増加状態のとき、さらに威力が上昇する"}, "levels": {"1": [613, 67]}, "limitBreaks": []},
    {"no": 134, "name": "次郎太刀-戦装束", "base": "次郎太刀", "costume": "戦装束", "rarity": "通常", "swordType": "大太刀", "yukari": ["ご神刀"], "secretColor": "赤", "skillValue": 27, "skillName": "正円一刀斬り", "skills": {"1": "【円型・大範囲】のト餓鬼を消去し、敵に【特小＋＋】ダメージを与える"}, "levels": {"1": [501, 71]}, "limitBreaks": []},
    {"no": 138, "name": "御手杵-戦装束", "base": "御手杵", "costume": "戦装束", "rarity": "通常", "swordType": "槍", "yukari": ["天下三名槍"], "secretColor": "赤", "skillValue": 22, "skillName": "必中正円突き", "skills": {"1": "指定した1箇所【円型・特小範囲】のト餓鬼を消去し、敵に【小＋】ダメージを与える"}, "levels": {"1": [461, 60]}, "limitBreaks": []},
];

// 経験値表（全キャラ共通・レアも同じ）
// { レベル: そのレベルから次のレベルに上がるのに必要な累計経験値（ゲーム画面の「/」の右の数） }
const EXP_TABLE = {"1": 9, "4": 258, "5": 441, "6": 683, "7": 989, "8": 1363, "9": 1809, "10": 2330, "11": 2928, "12": 3609, "13": 4373, "14": 5224, "15": 6165, "16": 7198, "17": 8326, "18": 9550, "19": 10873, "20": 12298, "22": 15458, "23": 17199, "24": 19049, "25": 21009, "26": 23083, "28": 27576, "29": 30000};

// 限界突破（奥義強化）に必要な強化片と小判
// { 通常 / レア: { 今の段階: { shards: 強化片, coins: 小判 } } }（わかっている段階だけ）
const SKILL_UPGRADES = {"通常": {}, "レア": {"2": {"shards": 50, "coins": 10000}}};
