// ===== 素材の固定データ =====
// このファイルは tools/convert_master.py で data/master.xlsx から作っています。
// 直接書き換えても動きますが、次に変換したときに Excel の内容で上書きされます。

const MATERIAL_CATEGORIES = ["贈物", "経験値の書"];

const MATERIALS = [
    {"name": "お花", "category": "贈物", "source": "ドロップ"},
    {"name": "水", "category": "贈物", "source": "ドロップ"},
    {"name": "葉っぱ", "category": "贈物", "source": "ドロップ"},
    {"name": "火打ち石", "category": "贈物", "source": "ドロップ"},
    {"name": "桃", "category": "贈物", "source": "ドロップ"},
    {"name": "木の枝", "category": "贈物", "source": "ドロップ"},
    {"name": "卵", "category": "贈物", "source": "ドロップ"},
    {"name": "お魚", "category": "贈物", "source": "ドロップ"},
    {"name": "サンゴ", "category": "贈物", "source": "ドロップ"},
    {"name": "丸太", "category": "贈物", "source": "ドロップ"},
    {"name": "骨付き肉", "category": "贈物", "source": "ドロップ"},
    {"name": "粘土", "category": "贈物", "source": "ドロップ"},
    {"name": "お米", "category": "贈物", "source": "ドロップ"},
    {"name": "鉄", "category": "贈物", "source": "ドロップ"},
    {"name": "昆布", "category": "贈物", "source": "ドロップ"},
    {"name": "ふさふさの毛", "category": "贈物", "source": "ドロップ"},
    {"name": "大豆", "category": "贈物", "source": "ドロップ"},
    {"name": "麦", "category": "贈物", "source": "ドロップ"},
    {"name": "塩", "category": "贈物", "source": "ドロップ"},
    {"name": "サイコロ", "category": "贈物", "source": "ドロップ"},
    {"name": "油", "category": "贈物", "source": "ドロップ"},
    {"name": "ネジ", "category": "贈物", "source": "ドロップ"},
    {"name": "花の蜜", "category": "贈物", "source": "合成", "recipe": {"水": 1, "お花": 2}},
    {"name": "紙", "category": "贈物", "source": "合成", "recipe": {"木の枝": 1, "丸太": 1, "水": 1}},
    {"name": "みかげ石", "category": "贈物", "source": "ドロップ"},
    {"name": "ろうそく", "category": "贈物", "source": "ドロップ"},
    {"name": "手旗", "category": "贈物", "source": "ドロップ"},
    {"name": "書き物道具", "category": "贈物", "source": "合成"},
    {"name": "鬼のツノ", "category": "贈物", "source": "ドロップ"},
    {"name": "獣の牙", "category": "贈物", "source": "ドロップ"},
    {"name": "トラの毛皮", "category": "贈物", "source": "ドロップ"},
    {"name": "元結", "category": "贈物", "source": "ドロップ", "effect": "レアドロップ"},
    {"name": "花札", "category": "贈物", "source": "合成", "recipe": {"紙": 5, "お花": 5, "筆": 2, "サンゴ": 2}},
    {"name": "天ぷら", "category": "贈物", "source": "合成", "recipe": {"油": 2, "お魚": 2, "卵": 1, "麦": 1}},
    {"name": "そろばん", "category": "贈物", "source": "合成", "recipe": {"とんかち": 5, "鉄": 3, "木の枝": 1, "丸太": 1}},
    {"name": "打刀の心得", "category": "贈物", "source": "合成", "recipe": {"紙": 6, "筆": 6, "鬼のツノ": 4}},
    {"name": "筆", "category": "贈物", "source": "合成", "recipe": {"木の枝": 2, "ふさふさの毛": 1}},
    {"name": "とんかち", "category": "贈物", "source": "合成", "recipe": {"丸太": 1, "鉄": 1}},
    {"name": "真珠貝", "category": "贈物", "source": "ドロップ"},
    {"name": "カニのはさみ", "category": "贈物", "source": "ドロップ"},
    {"name": "ウロコ", "category": "贈物", "source": "ドロップ"},
    {"name": "羽衣", "category": "贈物", "source": "ドロップ"},
    {"name": "囲碁", "category": "贈物", "source": "合成", "recipe": {"丸太": 1, "獣の牙": 1, "お椀": 1, "ウロコ": 1}},
    {"name": "お椀", "category": "贈物", "source": "合成", "recipe": {"粘土": 1, "火打ち石": 1}},
    {"name": "お味噌汁", "category": "贈物", "source": "合成", "recipe": {"味噌": 2, "葉っぱ": 1, "水": 1, "昆布": 1}},
    {"name": "味噌", "category": "贈物", "source": "合成", "recipe": {"お米": 1, "大豆": 1, "塩": 1}},
    {"name": "短刀の心得", "category": "贈物", "source": "合成", "recipe": {"紙": 6, "筆": 6, "粘土": 12}},
    {"name": "赤の絵具", "category": "贈物", "source": "イベント"},
    {"name": "青の絵具", "category": "贈物", "source": "イベント"},
    {"name": "黄の絵具", "category": "贈物", "source": "イベント"},
    {"name": "経験値の書・小", "category": "経験値の書", "source": "", "effect": "経験値+150", "exp": 150},
    {"name": "経験値の書・中", "category": "経験値の書", "source": "", "effect": "経験値+1200", "exp": 1200},
    {"name": "経験値の書・大", "category": "経験値の書", "source": "", "effect": "経験値+6000", "exp": 6000},
];
